### ISSUE TITLE
Create Hover effect

### ISSUE THREAD

**Issue by warrenferns** [githubcrce/Quiz-Generator#5]
**Describe the solution you'd like**
Hover effect needs to be implemented on answers as well as 'Next' and all other buttons wherever possible

**Comment by falguni-k** [comment]
Hi, I would like to work on this issue.
What kind of highlight do you want to add upon hover?

**Comment by alammoiz** [comment]
@warrenferns I would love to do this task, Please assign it to me

**Comment by shikhar13012001** [comment]
Can I work on this issue?

**Comment by falguni-k** [comment]
Hey, the hover over options is getting overridden by some styles. Can you help?

**Comment by Irfan7014** [comment]
I'll can work on this issue
